### ISSUE TITLE
Ability to replay Surface Pro 4 touchscreen HID events?

### ISSUE THREAD

**Issue by mgcrea** [bentiss/hid-replay#4]
Hey @bentiss, I've seen that you've [recently posted](https://lkml.org/lkml/2016/5/19/81) a working driver for the SP3 device. I'm about to receive an SP4 and was wondering if you had any inputs/feedback regarding developing a driver for it (disclaimer, I'm a total noob in linux driver dev), but seeing that the code is relatively small (300loc), I'm wondering:
- Do you think your current driver could be easily ported to this new hardware?
- What would be the proper workflow to work on it, use this lib first to debug events? Would this lib work?

Thanks a lot!

**Comment by bentiss** [comment]
Unfortunately, the Surface Pro 4 is using a completely different driver:
https://github.com/jimdigriz/intel-precise-touch

The touchscreen is connected over PCI so that the GPU can access it, but there is currently no known implementation of such driver (see the github project above).

So basically, supporting the touchscreen of the Surface Pro 4 is a whole different stroy than the Surface 3, and there is no plan for it right now.

**Comment by mgcrea** [comment]
@bentiss thanks for the insights!
